### PR TITLE
Update Vagrantfile to vagrant 1.2, fix some script quirks

### PR DESCRIPTION
**Pull request by weltenwort**
- the Vagrantfile is now compatible with vagrant 1.2
- the ardrone2.sh helper script halts the VM after a build
- correct permissions for the build dependencies are set

### CODE REVIEW

**Comment by rmehner** [comment]
Looks good, thank you very much. Does this run on Vagrant < 1.2 too, or should we add a note on the README?

**Comment by weltenwort** [comment]
Thanks for merging so quickly! It should work with vagrant >= 1.1, but I only tested it with 1.2.2, which is the current version.

**Comment by rmehner** [comment]
Fair enough, a simple `gem install vagrant` will get you the latest version anyway.

**Comment by felixge** [comment]
@weltenwort @rmehner :sparkling_heart: thx!

**Pull request merged**
